# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'UITextViewGestureRecognizerDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Masonry', '~> 0.6.4'
  # Pods for UITextViewGestureRecognizerDemo

  target 'UITextViewGestureRecognizerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UITextViewGestureRecognizerDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
